version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "area/dependency"
    commit_message:
      prefix: "chore"
      include_scope: true
